let a={
    cseAll:{
        sub:{
          name:`c`,
          pdf:`c.pdf` 
        },
        sub:{
          name:`python`,
          pdf:`python.pdf`
        },
        sub:{
            name:`python`,
            pdf:`python.pdf`
        },
          sub1:{
            name:`python`,
            pdf:`python.pdf`
        },
        sub:{
          name:`python`,
          pdf:`python.pdf`
      },
      sub:{
        name:`python`,
        pdf:`python.pdf`
    },
    sub:{
      name:`python`,
      pdf:`python.pdf`
  }        
    }
}
module.exports=a